<template src="./Riders.template.html"></template>
<script setup>
import { Search, Refresh, More, Delete, Sort, Plus } from '@element-plus/icons-vue';
import ImageUpload from '@/components/ImageUpload.vue';
import PageStateAlert from '@/components/PageStateAlert.vue';
import ResponsiveActions from '@/components/ResponsiveActions.vue';
import { useRidersPage } from './ridersHelpers';

const {
  isMobile,
  pageSize,
  loading,
  loadError,
  riders,
  currentPage,
  total,
  searchKeyword,
  deletingRider,
  deletingOrders,
  resettingPassword,
  addDialogVisible,
  addingRider,
  reorganizing,
  clearing,
  detailVisible,
  detail,
  riderEditVisible,
  savingRiderEdit,
  uploadingRiderIdCard,
  riderEditForm,
  newRider,
  inviteDialogVisible,
  creatingInvite,
  inviteForm,
  inviteResult,
  reviewManageVisible,
  reviewTargetRider,
  riderReviewsLoading,
  riderReviews,
  riderReviewDialogVisible,
  riderReviewEditingId,
  riderReviewSaving,
  uploadingRiderReviewImage,
  riderReviewForm,
  formatRoleId,
  loadRiders,
  handleSearch,
  handlePageChange,
  handleSizeChange,
  handleMobileAction,
  formatTime,
  formatRating,
  showAddDialog,
  openInviteDialog,
  createInviteLink,
  copyInviteUrl,
  formatInviteDateTime,
  getInviteRemainingUses,
  handleAddRider,
  handleReorganizeIds,
  handleResetPassword,
  handleDeleteRiderOrders,
  handleDeleteRider,
  openDetail,
  openRiderEditDialog,
  handleRiderIdCardChange,
  saveRiderEdit,
  formatOnboardingSource,
  formatOnboardingType,
  openRiderReviewManage,
  loadRiderReviews,
  openCreateRiderReviewDialog,
  openEditRiderReviewDialog,
  handleRiderReviewImageChange,
  removeRiderReviewImage,
  saveRiderReview,
  handleDeleteRiderReview,
  handleClearAllRiders,
  getRankName,
  getRankType
} = useRidersPage();
</script>

<style scoped lang="css" src="./Riders.css"></style>
