import config from "./config";
import getLocalDB from "./db";
import { createConsumerServiceRuntime } from "../../packages/mobile-core/src/consumer-service-runtime.js";

const serviceRuntime = createConsumerServiceRuntime({
  config,
  getLocalDB,
  baseUrl: config.API_BASE_URL,
  timeout: config.TIMEOUT,
  productShopMode: "products-query",
  supportsShopCategory: true,
  isDev: Boolean(config.isDev),
  logger: console,
  uniApp: uni,
});

export const {
  getSyncService,
  request,
  getBaseUrl,
  BASE_URL,
  fetchShopCategories,
  fetchShops,
  fetchShopDetail,
  fetchShopMenu,
  fetchOrders,
  fetchOrderDetail,
  createOrder,
  consultMedicineAssistant,
  listDiningBuddyParties,
  createDiningBuddyParty,
  joinDiningBuddyParty,
  fetchDiningBuddyMessages,
  sendDiningBuddyMessage,
  createDiningBuddyReport,
  createAfterSales,
  fetchAfterSalesList,
  fetchGroupbuyVouchers,
  fetchVoucherQRCode,
  fetchUserCoupons,
  uploadAfterSalesEvidence,
  uploadCommonAsset,
  uploadCommonImage,
  buildAuthorizationHeader,
  readAuthorizationHeader,
  fetchUser,
  fetchUserFavorites,
  addUserFavorite,
  deleteUserFavorite,
  fetchUserFavoriteStatus,
  fetchUserReviews,
  login,
  register,
  consumeWechatSession,
  wechatBindLogin,
  requestSMSCode,
  verifySMSCodeCheck,
  changeUserPhone,
  updateUserProfile,
  fetchUserAddresses,
  fetchDefaultUserAddress,
  recordPhoneContactClick,
  createRTCCall,
  getRTCCall,
  listRTCCallHistory,
  updateRTCCallStatus,
  createUserAddress,
  updateUserAddress,
  deleteUserAddress,
  setDefaultUserAddress,
  fetchPointsBalance,
  fetchPointsGoods,
  redeemPoints,
  earnPoints,
  refundPoints,
  submitCooperation,
  fetchInviteCode,
  recordInviteShare,
  fetchPublicRuntimeSettings,
  fetchPublicCharitySettings,
  fetchPublicVIPSettings,
  fetchCategories,
  fetchProducts,
  fetchMenuItems,
  fetchBanners,
  fetchProductDetail,
  fetchHomeFeed,
  fetchWeather,
  reverseGeocode,
  fetchConversations,
  upsertConversation,
  markConversationRead,
  markAllConversationsRead,
  fetchHistory,
  fetchNotificationList,
  fetchNotificationDetail,
  markNotificationRead,
  markAllNotificationsRead,
  registerPushDevice,
  unregisterPushDevice,
  ackPushMessage,
  getCachedConsumerAuthRuntimeSettings,
  loadConsumerAuthRuntimeSettings,
  resetConsumerAuthRuntimeSettings,
} = serviceRuntime;

export {
  DEFAULT_CONSUMER_AUTH_RUNTIME_SETTINGS,
} from "../../packages/mobile-core/src/consumer-service-runtime.js";
