-- 财务中心 & 钱包模块 migration
-- 执行前确保已 USE 对应数据库

CREATE TABLE IF NOT EXISTS `wallet_accounts` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` varchar(50) NOT NULL,
  `user_type` varchar(20) NOT NULL COMMENT 'customer/rider/merchant',
  `balance` bigint NOT NULL DEFAULT 0 COMMENT '余额（分）',
  `frozen_balance` bigint NOT NULL DEFAULT 0,
  `total_balance` bigint NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `last_transaction_id` varchar(64) DEFAULT NULL,
  `last_transaction_at` datetime DEFAULT NULL,
  `daily_recharge_amount` bigint DEFAULT 0,
  `daily_withdraw_amount` bigint DEFAULT 0,
  `daily_payment_amount` bigint DEFAULT 0,
  `daily_recharge_count` int DEFAULT 0,
  `daily_withdraw_count` int DEFAULT 0,
  `last_daily_reset_at` date DEFAULT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'active' COMMENT 'active/frozen/closed',
  `frozen_reason` text,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_id` (`user_id`),
  KEY `idx_user_type` (`user_type`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `wallet_transactions` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `transaction_id` varchar(64) NOT NULL,
  `transaction_id_raw` varchar(128) DEFAULT NULL,
  `idempotency_key` varchar(80) DEFAULT NULL,
  `idempotency_key_raw` varchar(160) DEFAULT NULL,
  `user_id` varchar(50) NOT NULL,
  `user_type` varchar(20) NOT NULL,
  `type` varchar(30) NOT NULL COMMENT 'payment/refund/recharge/withdraw/compensation/admin_add_balance/admin_deduct_balance',
  `business_type` varchar(30) DEFAULT NULL,
  `business_id` varchar(64) DEFAULT NULL,
  `amount` bigint NOT NULL,
  `balance_before` bigint NOT NULL,
  `balance_after` bigint NOT NULL,
  `payment_method` varchar(20) DEFAULT 'ifpay',
  `payment_channel` varchar(50) DEFAULT NULL,
  `third_party_order_id` varchar(128) DEFAULT NULL,
  `third_party_transaction_id` varchar(128) DEFAULT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'pending' COMMENT 'pending/processing/success/failed/cancelled',
  `description` text,
  `remark` text,
  `operator_id` varchar(50) DEFAULT NULL,
  `operator_name` varchar(100) DEFAULT NULL,
  `operator_ip` varchar(50) DEFAULT NULL,
  `signature` varchar(256) DEFAULT NULL,
  `request_data` text,
  `response_data` text,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `completed_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_transaction_id` (`transaction_id`),
  UNIQUE KEY `uk_idempotency_key` (`idempotency_key`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_user_type` (`user_type`),
  KEY `idx_type` (`type`),
  KEY `idx_status` (`status`),
  KEY `idx_business_id` (`business_id`),
  KEY `idx_transaction_id_raw` (`transaction_id_raw`),
  KEY `idx_idempotency_key_raw` (`idempotency_key_raw`),
  KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `recharge_orders` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `order_id` varchar(64) NOT NULL,
  `transaction_id` varchar(64) DEFAULT NULL,
  `transaction_id_raw` varchar(128) DEFAULT NULL,
  `user_id` varchar(50) NOT NULL,
  `user_type` varchar(20) NOT NULL,
  `amount` bigint NOT NULL,
  `actual_amount` bigint DEFAULT NULL,
  `payment_method` varchar(20) NOT NULL,
  `payment_channel` varchar(50) DEFAULT NULL,
  `third_party_order_id` varchar(128) DEFAULT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'pending',
  `callback_data` text,
  `callback_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `paid_at` datetime DEFAULT NULL,
  `expired_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_order_id` (`order_id`),
  UNIQUE KEY `uk_third_party_order_id` (`third_party_order_id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_transaction_id_raw` (`transaction_id_raw`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `withdraw_requests` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `request_id` varchar(64) NOT NULL,
  `request_id_raw` varchar(128) DEFAULT NULL,
  `transaction_id` varchar(64) DEFAULT NULL,
  `transaction_id_raw` varchar(128) DEFAULT NULL,
  `user_id` varchar(50) NOT NULL,
  `user_type` varchar(20) NOT NULL,
  `amount` bigint NOT NULL,
  `fee` bigint DEFAULT 0,
  `actual_amount` bigint NOT NULL,
  `withdraw_method` varchar(20) NOT NULL,
  `withdraw_account` varchar(128) NOT NULL,
  `withdraw_name` varchar(100) DEFAULT NULL,
  `bank_name` varchar(100) DEFAULT NULL,
  `bank_branch` varchar(200) DEFAULT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'pending' COMMENT 'pending/approved/rejected/completed/failed',
  `reviewer_id` varchar(50) DEFAULT NULL,
  `reviewer_name` varchar(100) DEFAULT NULL,
  `review_remark` text,
  `reviewed_at` datetime DEFAULT NULL,
  `third_party_order_id` varchar(128) DEFAULT NULL,
  `transfer_result` text,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `completed_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_request_id` (`request_id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_request_id_raw` (`request_id_raw`),
  KEY `idx_transaction_id_raw` (`transaction_id_raw`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `admin_wallet_operations` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `operation_id` varchar(64) NOT NULL,
  `operation_id_raw` varchar(128) DEFAULT NULL,
  `transaction_id` varchar(64) DEFAULT NULL,
  `transaction_id_raw` varchar(128) DEFAULT NULL,
  `target_user_id` varchar(50) NOT NULL,
  `target_user_type` varchar(20) NOT NULL,
  `operation_type` varchar(20) NOT NULL COMMENT 'add_balance/deduct_balance/freeze/unfreeze',
  `amount` bigint NOT NULL,
  `admin_id` varchar(50) NOT NULL,
  `admin_name` varchar(100) NOT NULL,
  `admin_ip` varchar(50) NOT NULL,
  `reason` text NOT NULL,
  `remark` text,
  `requires_approval` tinyint(1) DEFAULT 0,
  `approver_id` varchar(50) DEFAULT NULL,
  `approver_name` varchar(100) DEFAULT NULL,
  `approval_status` varchar(20) DEFAULT NULL,
  `approved_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_operation_id` (`operation_id`),
  KEY `idx_operation_id_raw` (`operation_id_raw`),
  KEY `idx_transaction_id_raw` (`transaction_id_raw`),
  KEY `idx_target_user_id` (`target_user_id`),
  KEY `idx_admin_id` (`admin_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `payment_callbacks` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `callback_id` varchar(64) NOT NULL,
  `callback_id_raw` varchar(128) DEFAULT NULL,
  `channel` varchar(20) NOT NULL,
  `event_type` varchar(50) DEFAULT NULL,
  `third_party_order_id` varchar(128) DEFAULT NULL,
  `transaction_id` varchar(64) DEFAULT NULL,
  `transaction_id_raw` varchar(128) DEFAULT NULL,
  `nonce` varchar(100) DEFAULT NULL,
  `signature` varchar(512) DEFAULT NULL,
  `verified` tinyint(1) DEFAULT 0,
  `replay_fingerprint` varchar(128) DEFAULT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'pending',
  `request_headers` text,
  `request_body` longtext,
  `response_body` text,
  `processed_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_callback_id` (`callback_id`),
  KEY `idx_callback_id_raw` (`callback_id_raw`),
  KEY `idx_channel` (`channel`),
  KEY `idx_transaction_id` (`transaction_id`),
  KEY `idx_transaction_id_raw` (`transaction_id_raw`),
  KEY `idx_replay_fingerprint` (`replay_fingerprint`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `idempotency_records` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `idempotency_key` varchar(120) NOT NULL,
  `idempotency_key_raw` varchar(200) DEFAULT NULL,
  `scope` varchar(64) NOT NULL,
  `request_hash` varchar(128) DEFAULT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'processing',
  `response_data` longtext,
  `expired_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_idempotency_key` (`idempotency_key`),
  KEY `idx_idempotency_key_raw` (`idempotency_key_raw`),
  KEY `idx_scope` (`scope`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `reconciliation_tasks` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `task_id` varchar(64) NOT NULL,
  `task_id_raw` varchar(128) DEFAULT NULL,
  `task_type` varchar(30) NOT NULL,
  `channel` varchar(20) DEFAULT NULL,
  `reconcile_date` date NOT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'pending',
  `total_records` int DEFAULT 0,
  `matched_records` int DEFAULT 0,
  `mismatch_records` int DEFAULT 0,
  `error_message` text,
  `result_data` longtext,
  `started_at` datetime DEFAULT NULL,
  `completed_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_task_id` (`task_id`),
  KEY `idx_task_id_raw` (`task_id_raw`),
  KEY `idx_task_type` (`task_type`),
  KEY `idx_reconcile_date` (`reconcile_date`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 给 orders 表补充支付字段（如果不存在）
ALTER TABLE `orders`
  ADD COLUMN IF NOT EXISTS `payment_method` varchar(20) DEFAULT 'ifpay',
  ADD COLUMN IF NOT EXISTS `payment_status` varchar(20) DEFAULT 'unpaid',
  ADD COLUMN IF NOT EXISTS `payment_transaction_id` varchar(64) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `payment_time` datetime DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `refund_transaction_id` varchar(64) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `refund_amount` bigint DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `refund_time` datetime DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `platform_commission` bigint DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `rider_income` bigint DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `merchant_income` bigint DEFAULT 0;
